import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const pairs = [
['STAGE 02 / 讓好成果可以重複','STAGE 02 / MAKE RESULTS REPEATABLE'],['讓生意成長，不只靠你加班。','Grow beyond working longer hours.'],['把已經做得好的工作拆成流程，讓 AI 協助內容初稿、客服整理與營運彙整；你專注品質與關係。','Turn good work into a process. Let AI help draft content, organize customer service and summarize operations while you focus on quality and relationships.'],['固定的資料輸入格式','Consistent input formats'],['可重複使用的提示詞與 SOP','Reusable prompts and SOPs'],['品質檢查與人工接手機制','Quality checks and human handover rules'],['STAGE 03 / 探索下一個市場','STAGE 03 / EXPLORE YOUR NEXT MARKET'],['帶著一套系統，走向更大的舞台。','Take a proven system into a bigger market.'],['當既有流程穩定，再用 AI 協助研究新市場、整理產品回饋與比較成長方向。每一次擴大，都保留驗證與修正的空間。','Once existing workflows are stable, use AI to research new markets, organize product feedback and compare growth options. Leave room to validate and adjust at every step.'],['市場研究與待驗證假設','Market research and hypotheses to validate'],['可交接的營運方法','Transferable operating methods'],['擴大前的成本與品質檢查清單','Cost and quality checklist before scaling'],
['想主題、改文案，忙到忘了經營自己的品牌。','Planning and rewriting content leaves no time for your own brand.'],['每個平台都要重新寫一篇，內容做了很多，卻缺少一致的品牌觀點。','Each platform needs another draft. You create plenty of content but lack a consistent brand perspective.'],['你的專業觀點、作品與原始素材','Your expertise, work and original material'],['整理主題・延伸不同平台的初稿','Organize themes · Draft for different platforms'],['補上經驗・核對內容・決定發布','Add experience · Verify content · Decide what to publish'],['內容主題庫 ＋ 文案模板 ＋ 發布檢查清單','Topic library + Copy templates + Publishing checklist'],['相同的問題，每天都要重新回答。','Answering the same questions every day.'],['訊息分散在不同地方，常見問題與重要需求容易一起被埋沒。','Scattered messages bury common questions and important requests.'],['已去識別的常見問題與服務規則','De-identified FAQs and service policies'],['分類問題・整理知識・草擬回覆','Classify questions · Organize knowledge · Draft replies'],['確認承諾・處理例外・維繫關係','Check commitments · Handle exceptions · Maintain relationships'],['常見問答庫 ＋ 回覆範本 ＋ 人工接手規則','FAQ library + Reply templates + Human handover rules'],['忙了一整週，還在複製貼上、整理報表。','A busy week, still copying data and compiling reports.'],['資料格式不一，每次統整都得重做，真正需要判斷的重點反而沒時間看。','Inconsistent formats mean rebuilding every report, leaving little time for decisions that matter.'],['格式一致的紀錄與報表欄位','Consistent records and report fields'],['彙整資料・摘要變化・標記待確認','Compile data · Summarize changes · Flag uncertainties'],['核對數字・釐清原因・決定行動','Verify numbers · Understand causes · Decide actions'],['資料格式 ＋ 週報模板 ＋ 數字核對清單','Data format + Weekly report template + Number verification checklist'],['想題 → 寫稿 → 改稿 → 再想題','Plan → Draft → Revise → Repeat'],['查看 → 分類 → 回覆 → 再回覆','Read → Classify → Reply → Repeat'],['蒐集 → 複製 → 核對 → 重做','Collect → Copy → Check → Repeat'],
['做出一份客戶看得懂的服務提案','Build a service proposal customers understand'],['整理你最想幫助的客戶、他遇到的問題，以及你能提供的價值。','Describe your ideal customer, their problem and the value you can provide.'],['請 AI 依據你的資料，整理需求、服務說明與一份提案骨架；未知的內容標記待確認。','Ask AI to organize needs, describe your service and outline a proposal based on your data. Flag unknown information for review.'],['找一位符合條件的潛在客戶訪談，記錄他是否看懂價值、願意進一步討論，以及仍有什麼疑問。','Interview a suitable prospect. Record whether they understand the value, want to discuss further and still have questions.'],['把一份專業素材，變成可延續的內容','Turn one piece of expertise into reusable content'],['選一份你擁有使用權的作品、文章或常見客戶問題，補上自己的觀點。','Choose work, an article or a common customer question you have permission to use. Add your own perspective.'],['請 AI 整理三個內容角度與一篇初稿，再依你使用的平台調整格式。','Ask AI for three content angles and one draft, then adapt the format to your platform.'],['核對事實、補上你的經驗，確認語氣與權利後再發布，記錄讀者提出的問題。','Verify facts, add your experience and check tone and rights before publishing. Record reader questions.'],['整理一份可以接手的常見問題庫','Create a reusable FAQ library'],['蒐集五個重複出現的問題，移除個資，附上已確認的服務規則與答案。','Collect five recurring questions, remove personal data and add verified service policies and answers.'],['請 AI 分類問題並草擬回覆；不確定、例外或涉及承諾的情況，標記交由你處理。','Ask AI to classify questions and draft replies. Flag uncertainties, exceptions and commitments for your review.'],['用不同問法測試答案，檢查是否漏掉限制或做出未授權承諾，留下人工接手規則。','Test varied wording. Check for missing limitations or unauthorized commitments and document human handover rules.'],['讓一份週報，從重做到重複使用','Make your weekly report reusable'],['挑一份最常整理的紀錄，統一欄位、日期與單位，建立一份小型範例。','Choose a recurring record. Standardize fields, dates and units, then create a small example.'],['請 AI 依固定欄位彙整，分開已知資料與待確認項目，不補猜缺少的數字。','Ask AI to summarize using fixed fields. Separate verified data from items to check. Do not invent missing numbers.'],['逐項比對原始資料，記錄總耗時、錯誤與修正，再保存成下次可用的模板。','Compare each item with the source. Record time, errors and corrections, then save a reusable template.'],
['先花一小段時間，從一個真實工作例子整理起，不必等資料全部齊全。','Start by organizing one real work example. You do not need all your data ready.'],['先挑一小份可信、可用的資料測試，確認來源與使用權，再逐步補齊。','Test a small, reliable dataset. Confirm its source and permission to use it, then expand gradually.'],['先記錄既有流程的耗時與品質，讓這次試行有可以比較的基準。','Record the time and quality of your existing workflow to establish a comparison baseline.'],['此階段先驗證需求，避免一次投入太多工具。','Validate demand first and avoid investing in too many tools at once.'],['此階段先找出可重複的步驟，降低每次從頭開始的負擔。','Identify repeatable steps to reduce the need to start from scratch.'],['此階段先檢查交接、權限與成本，再評估是否擴大。','Review handover, permissions and costs before deciding to scale.'],['我的 AI 起步清單','My AI starter checklist'],['目前階段：','Current stage: '],['優先問題：','Priority challenge: '],['資料狀況：','Data readiness: '],['第一個任務：','First mission: '],['這是依選項整理的試行建議，實際合作範圍另行討論。','These pilot suggestions reflect your selections. Actual collaboration scope will be discussed separately.'],['您好，我想討論以下工作題目：','Hello, I would like to discuss the following work challenge:'],['起步清單已複製，可以貼到你的筆記中。','Checklist copied. You can paste it into your notes.'],['瀏覽器未開放複製權限，請選取上方清單文字複製。','Clipboard access is unavailable. Select and copy the checklist above.'],
['TMARSBASE 創火星基地｜一人企業的 AI 成長基地','TMARSBASE | The AI Growth Base for Solo Businesses'],
['協助一人企業與精實團隊運用 AI，從需求驗證、內容與客戶服務，到可複製的營運流程。活下來、長起來，朝更大的可能前進。','Helping solo businesses and lean teams use AI to validate demand, create content, serve customers and build repeatable operations.'],
['跳到主要內容','Skip to main content'],['TMARSBASE 創火星基地首頁','TMARSBASE home'],['主要導覽','Main navigation'],['選單','Menu'],['關閉','Off'],['創火星基地創辦人黃大成','Blake Huang, founder of TMARSBASE'],
['給一人企業與精實團隊的 AI 成長基地','THE AI GROWTH BASE FOR SOLO BUSINESSES & LEAN TEAMS'],['從一個人，到更大的可能','START SOLO. BUILD WHAT COMES NEXT.'],
['一個人出發，','Start with you.'],['長出一間','Build a business'],['有未來的公司。','with a future.'],
['讓 AI 接住重複工作，讓你專注創造價值。','Let AI handle repetitive work so you can focus on creating value.'],['從第一筆生意、可複製的交付，到更大的市場，','From your first sale to repeatable delivery and new markets,'],['創火星基地陪你把成長的方法，一步步做出來。','TMARSBASE helps you build your next step, one workflow at a time.'],
['找到我的 AI 成長起點','Find my AI starting point'],['找到我的起點','Find my starting point'],['探索成長路線','Explore the growth path'],['成長路線','Growth path'],['AI 工作實驗室','AI Workflow Lab'],['合作方案','Services (中文)'],['基地夥伴','Our crew (中文)'],
['01 / 生存','01 / SURVIVE'],['02 / 成長','02 / GROW'],['找到願意付費的需求','Find demand worth paying for'],['建立可複製的工作系統','Build repeatable work systems'],['你的下一個可能，正在成形','Your next possibility is taking shape'],['一人企業的起點，一人獨角獸的想像。','A solo business today. A bigger possibility tomorrow.'],['向下探索品牌理念','Explore our purpose'],['向下探索','Explore below'],
['01 / 我們為何出發','01 / WHY WE EXIST'],['公司可以很小。','Your company can be small.'],['你的可能，不必。','Your possibilities do not have to be.'],['創業最難的，往往不是缺少想法，','Starting a business is rarely about a lack of ideas.'],['而是你得同時扮演每一個角色。','It is about having to play every role yourself.'],
['找客戶、做內容、回訊息、交付成果，還要顧好營運。當一切都依賴你的時間，成長就容易卡住。','Finding customers, creating content, answering messages, delivering work and running operations. When everything depends on your time, growth gets stuck.'],['我們想協助你把 AI 變成日常工作的一部分：','We help make AI part of your everyday work: '],['把時間找回來，把價值做出來，把生意長起來。','reclaim your time, create value and grow your business.'],['我們的願景','OUR VISION'],['讓更多一人企業活下來、長大，','Help more solo businesses survive and grow,'],['有機會走向「一人獨角獸」。','with the possibility of becoming a one-person unicorn.'],['獨角獸是長期願景；成長需要市場驗證、持續執行與經營判斷。','A unicorn is a long-term aspiration. Growth requires market validation, sustained execution and business judgment.'],
['02 / 你的成長路線','02 / YOUR GROWTH PATH'],['不是每一步都要大。','Every step need not be big.'],['但每一步，都要往前。','Every step should move you forward.'],['先找到你現在的位置。','Start with where you are.'],['再讓 AI 幫上真正需要的忙。','Then put AI to work where it matters.'],['企業成長階段','Business growth stages'],['先活下來','Survive first'],['再長起來','Then grow'],['走得更遠','Go further'],['驗證需求，找到第一個收入引擎','Validate demand. Find your first revenue engine.'],['整理流程，讓好成果可以重複','Organize workflows. Make good results repeatable.'],['放大系統，探索下一個市場','Scale your systems. Explore your next market.'],['STAGE 01 / 找到第一個有效需求','STAGE 01 / VALIDATE YOUR FIRST REAL NEED'],['先做出，有人需要的價值。','Create value someone needs.'],['用 AI 整理客戶問題、設計提案與製作最小可行展示，把時間留給真實訪談與第一筆成交。','Use AI to organize customer problems, draft proposals and create a minimum viable demo. Save your time for real conversations and your first sale.'],['一句說得清楚的服務定位','A clear service proposition'],['一份可以拿去談的提案','A proposal ready for a customer conversation'],['一個能驗證需求的小型展示','A small demo to validate demand'],['從這裡開始','Start here'],
['03 / AI 工作實驗室','03 / AI WORKFLOW LAB'],['把你的分身，','Put your AI collaborator'],['放進工作流程。','inside your workflow.'],['選一項你熟悉的工作，','Choose a task you know well.'],['看看人與 AI 可以如何分工。','See how you and AI can share the work.'],['AI 工作情境','AI work scenarios'],['01 找到客戶','01 Find customers'],['02 內容行銷','02 Content marketing'],['03 客戶服務','03 Customer service'],['04 日常營運','04 Daily operations'],['情境示範','ILLUSTRATIVE SCENARIO'],['原本，你一個人做','BEFORE / YOU DO IT ALL'],['查資料、找痛點，','Research needs and pain points.'],['一份提案寫一整晚。','Spend all evening on one proposal.'],['資訊散在網站與筆記裡，每次接觸新客戶，又要從空白頁開始。','Information is scattered across websites and notes. Every new customer means starting from a blank page.'],['研究 → 整理 → 寫稿 → 重來','Research → Organize → Draft → Repeat'],['現在，讓 AI 協作','AFTER / WORK WITH AI'],['人與 AI 分工步驟','Human and AI workflow steps'],['你提供','YOU PROVIDE'],['AI 協助','AI ASSISTS'],['你把關','YOU REVIEW'],['客戶資料與服務優勢','Customer information and your service strengths'],['整理問題・產出提案初稿','Organize needs · Draft a proposal'],['確認事實・判斷需求・親自成交','Verify facts · Assess needs · Close the deal yourself'],['留下的工作資產','REUSABLE WORK ASSETS'],['客戶研究模板 ＋ 提案骨架 ＋ 跟進清單','Customer research template + Proposal outline + Follow-up checklist'],['流程示意，非客戶成效或自動執行服務','Illustrative workflow, not a client result or an automated service'],
['04 / 把可能變成做法','04 / HOW WE TURN IDEAS INTO ACTION'],['學會一個工具之後，','Learning a tool is a start.'],['還要留下一套方法。','Leave with a method that lasts.'],['從一項工作試起，','Pilot one task first.'],['直到你能接手、能檢查、能持續改進。','Build until you can own it, check it and keep improving it.'],['01 / 定位','01 / FOCUS'],['02 / 實作','02 / BUILD'],['03 / 驗證','03 / VALIDATE'],['04 / 交接','04 / HAND OVER'],['選對第一個問題','Choose the right first problem'],['盤點你的目標、日常工作與資料，選出最值得先改善的一件事。','Review your goals, daily tasks and data. Choose the one problem most worth solving first.'],['留下：優先清單與現況基準','Output: priorities and a baseline'],['做出可以用的版本','Build something you can use'],['把真實工作變成練習，用適合的工具做出最小可行流程。','Practice with real work and suitable tools to build a minimum viable workflow.'],['留下：可操作的流程或原型','Output: a working process or prototype'],['用證據決定下一步','Use evidence to choose the next step'],['檢查時間、品質與人工修正量，找出有效的部分與失敗的原因。','Check time, quality and manual corrections to identify what works and why something fails.'],['留下：測試紀錄與改善清單','Output: test records and improvements'],['讓方法留在你手上','Keep the method in your hands'],['整理 SOP、提示詞與例外處理，讓下一次工作有方法可循。','Document SOPs, prompts and exceptions so your next task has a clear process.'],['留下：SOP 與持續改善節奏','Output: SOPs and a routine for improvement'],
['05 / 現在，換你啟動','05 / YOUR TURN TO LAUNCH'],['不用準備好一切才開始','YOU DO NOT NEED EVERYTHING READY'],['你的 AI 第一站，','Your first AI mission.'],['從哪裡開始？','Where will you start?'],['選出目前最接近你的狀況，','Choose the situation closest to yours.'],['帶走一份可以開始行動的起步清單。','Take away a checklist you can act on.'],['依選項提供建議，無需登入。','Suggestions based on your selections. No login required.'],['答案只用於本頁整理，不會送出或儲存。','Answers stay on this page and are not sent or saved.'],['你現在在哪個階段？','What stage are you at?'],['哪件事最卡住你？','What is holding you back?'],['你手邊的資料準備好了嗎？','Is your data ready?'],['正要開始','Getting started'],['已有生意','Already in business'],['準備擴大','Ready to scale'],['找到穩定客源','Find consistent customers'],['持續產出內容','Create content consistently'],['回覆與服務客戶','Respond to and serve customers'],['重複的行政作業','Repetitive administrative work'],['還沒整理','Not organized yet'],['有一些資料','Some data available'],['已有固定流程','An established workflow'],['產生我的起步清單','Create my starter checklist'],['此互動需要 JavaScript；你也可以直接查看','This interaction requires JavaScript. You can also explore '],['你的第一個行動任務','YOUR FIRST ACTION'],['複製起步清單','Copy checklist'],['帶著清單來聊聊','Discuss my checklist'],['建議以小範圍試行為起點，實際合作範圍另行討論。','Start with a small pilot. The actual scope of collaboration will be discussed separately.'],
['06 / 你專注方向，我們一起做方法','06 / YOUR DIRECTION. OUR SHARED METHODS.'],['一個人創業，','Build your business solo.'],['也可以有基地。','Have a base behind you.'],['從 AI 需求診斷、實作培訓到流程試行，','From AI needs assessment and hands-on training to workflow pilots,'],['依你目前的題目，討論適合的合作方式。','we discuss the right collaboration for your current challenge.'],['探索合作方案','Explore services (中文)'],['01 / 顧問陪跑','01 / ADVISORY'],['把眼前的難題，','Take your current challenge.'],['拆成做得到的下一步。','Break it into achievable next steps.'],['釐清需求、選題、試行與驗收。','Clarify needs, set priorities, pilot and review.'],['02 / 實作培訓','02 / HANDS-ON TRAINING'],['讓團隊一起學，','Learn together as a team.'],['把方法帶回工作裡。','Bring the method back to work.'],['企業包班、情境練習與流程導入。','Team workshops, scenario practice and workflow adoption.'],['認識把商業、AI 與實作接起來的基地夥伴','Meet the crew connecting business, AI and hands-on practice'],['認識講師','Meet our instructors (中文)'],
['出發之前','BEFORE YOU START'],['你可能','A few things'],['還想知道。','you may want to know.'],['我只有一個人，也適合開始嗎？','Can I start if I work alone?'],['可以先從一項具體工作開始，例如整理客戶需求、製作內容初稿或彙整報表。先建立小範圍、可檢查的流程，再討論是否需要顧問協助。','Yes. Start with one specific task, such as organizing customer needs, drafting content or compiling reports. Build a small, reviewable workflow before deciding whether you need advisory support.'],['完全不懂程式，可以運用 AI 嗎？','Can I use AI without coding skills?'],['可以。起點是說清楚工作的輸入、產出與檢查方式。不同任務需要的工具與技術不同，涉及系統串接或開發時，再另外評估。','Yes. Begin by defining the inputs, outputs and review process. Tools vary by task; integration or development needs are assessed separately.'],['一定要先買很多 AI 工具嗎？','Do I need to buy many AI tools first?'],['先盤點你正在使用的工具與工作需求，再確認是否需要新增工具。付費訂閱、系統開發與硬體等費用，應先確認用途、範圍及預算。','Review your existing tools and work needs first. Confirm the purpose, scope and budget before adding subscriptions, development or hardware.'],['AI 能保證幫我賺錢，成為獨角獸嗎？','Can AI guarantee revenue or unicorn status?'],['不能保證。一人獨角獸是我們的長期願景。AI 可以協助研究、產出與流程整理，生意能否成長仍取決於市場需求、產品價值、執行與經營判斷。','No. A one-person unicorn is our long-term aspiration. AI can support research, production and workflows, but growth depends on demand, product value, execution and business judgment.'],['AI 做的內容，還需要人檢查嗎？','Does AI-generated work need human review?'],['需要。事實、對外承諾、客戶資料與重要決策都應有人負責。試行時會先討論資料權限、覆核方式與異常處理，再逐步擴大使用。','Yes. People remain responsible for facts, external commitments, customer data and important decisions. We discuss data access, review and exceptions before scaling a pilot.'],['我要怎麼開始合作？','How do I start working with you?'],['先完成本頁起步清單，或直接到合作方案頁整理需求。網站可協助產生郵件草稿，由你確認後寄出；合作內容、時程與費用會依需求討論。','Complete the starter checklist or outline your needs on our Chinese services page. The site prepares an email draft for you to review and send. Scope, timing and fees depend on your needs.'],
['下一間有可能的公司，','Your next business possibility'],['從你開始。','starts with you.'],['啟動我的第一個任務','Launch my first mission'],['從一項工作、一個流程、一次真實的改變開始。','Start with one task, one workflow and one real change.'],['讓一個人的可能，','Turn one person’s potential'],['長成一間有未來的公司。','into a business with a future.'],['聊聊你的下一步','Let’s discuss your next step'],['動態效果：開啟','Motion: on'],['動態效果：關閉','Motion: off'],['創火星基地股份有限公司','TMARSBASE'],['創火星基地','TMARSBASE'],
];
// Replace complete phrases first to avoid translating fragments prematurely.
const translate = value => pairs.toSorted((a,b)=>b[0].length-a[0].length).reduce((s,[zh,en])=>s.split(zh).join(en),value);
const source=readFileSync('scripts/home.zh.html','utf8');
const switcher='<div class="language-switch" aria-label="Language"><a href="/tmarsbase/" lang="zh-Hant">繁中</a><span aria-hidden="true">/</span><a href="/tmarsbase/en/" lang="en">EN</a></div>';
const alternates='<link rel="alternate" hreflang="zh-Hant" href="https://tmarsbase.tw/tmarsbase/"><link rel="alternate" hreflang="en" href="https://tmarsbase.tw/tmarsbase/en/"><link rel="alternate" hreflang="x-default" href="https://tmarsbase.tw/">';
const zh=source.replace('</head>',alternates+'</head>').replace('</nav>','</nav>'+switcher);
writeFileSync('dist/tmarsbase/index.html',zh);
writeFileSync('dist/index.html',zh);
let en=translate(source).replace('lang="zh-Hant"','lang="en"').replace('content="zh_TW"','content="en_US"').replaceAll('https://tmarsbase.tw/tmarsbase/','https://tmarsbase.tw/tmarsbase/en/').replace('src="/assets/mars-ui.js"','src="/assets/mars-ui-en.js"').replace('</head>',alternates+'</head>').replace('</nav>','</nav>'+switcher);
en=en.replaceAll('href="/tmarsbase/#','href="/tmarsbase/en/#').replaceAll('href="/tmarsbase/"','href="/tmarsbase/en/"');
// The language control must always point to its explicit language target.
en=en.replace('href="/tmarsbase/en/" lang="zh-Hant"','href="/tmarsbase/" lang="zh-Hant"');
mkdirSync('dist/tmarsbase/en',{recursive:true});writeFileSync('dist/tmarsbase/en/index.html',en);
writeFileSync('dist/assets/mars-ui-en.js',translate(readFileSync('dist/assets/mars-ui.js','utf8')).replace("'Off <span>−</span>'", "'Close <span>−</span>'"));
const css='\n.language-switch{display:flex;align-items:center;gap:8px;font-size:13px;white-space:nowrap;color:#ff8354}.language-switch a{color:inherit;padding:8px 2px}.language-switch a:focus-visible{outline:2px solid #ff8354;outline-offset:3px}html[lang="en"] .hero h1{font-size:clamp(48px,6.6vw,104px)}html[lang="en"] .hero-description{max-width:540px}html[lang="en"] .main-nav{gap:18px}html[lang="en"] .nav-cta{font-size:12px} @media(max-width:1100px){html[lang="en"] .nav-cta{display:none}} @media(max-width:800px){.language-switch{margin-left:auto;margin-right:12px}.masthead .menu-toggle{order:4}html[lang="en"] .hero h1{font-size:clamp(43px,9vw,72px)}html[lang="en"] .orbit-label strong{max-width:150px;font-size:12px}html[lang="en"] .option-row{flex-wrap:wrap}}\n';
writeFileSync('dist/assets/mars.css',readFileSync('scripts/mars.base.css','utf8')+css);
